### PR TITLE
Support React 16

### PR DESCRIPTION
**Pull request by jussikinnula**
This PR just adds React 16 support, while allows also to use React 15. I have tested and everything works perfectly with React 16 as well.

### CODE REVIEW

**Comment by maisano** [comment]
thank you! i hadn't gotten around to doing this yet. one small request however–can you amend the commit to remove the version bump? i can take care of that :)

**Comment by jussikinnula** [comment]
I removed the version bump now.

**Comment by maisano** [comment]
thanks @jussikinnula!

**Comment by holman** [comment]
It's a minor thing, but can we get a new release for this change? Cheers!

**Comment by maisano** [comment]
yes! sorry about that–it's been a wild week. just published `1.1.2`.

✌️

**Pull request merged**
