### PR TITLE
Adding TypeScript support

### PR DESCRIPTION
**Pull request by jakelauer**
Pretty self explanatory!

### CODE REVIEW

**Comment by jjnistico** [comment]
Did you mean to extend AnimatedSwitchProps for AnimatedRouteProps instead of extending RouteProps?

**Comment by hellocontrol-bng** [comment]
Actually, yeah, it should extend both.

**Review by ChaseH88 — APPROVED** [review]

**Comment by stevreeper** [comment]
Isn't this production ready? I was planning on using the library but needed the typescript support

**Comment by felipearosemena** [comment]
Any update on this?

**Comment by NoahFiner** [comment]
+1, would really like this merged

**Comment by maisano** [comment]
Hi–thanks for opening this PR @jakelauer! Sorry it's taken me so long to get to it. It's been, uhh, quite a year.

That said, as someone who doesn't use TypeScript with React, I'm not entirely keen on merging this, especially as it's another vector of maintaining this library (which, honestly, doesn't see much of my time these days).

I think this patch would be better suited for DefinitelyTyped. Apologies if that's a disappointing answer!

**Comment by TheDSCPL** [comment]
Ok, boomer

**Comment by TheDSCPL** [comment]
@maisano Ok, boomer

**Comment by jacobangel** [comment]
I deleted a comment that made a disrespectful comment to the maintainer of this project. This is free software maintained voluntarily in free time. While I understand there may be frustration with our decision, please keep the discourse civil and on the merits of the technology. Ad hominem is not a great way to encourage anyone to change their position.

**Comment by TheDSCPL** [comment]
"Ok boomer" is a common expression used to describe people who refuse to advance with the times. It wasn't an ad hominen informal falacy. If there was a facepalm reaction in Github, I would have used it instead. Didn't mean to insult. Sorry.

As this is an important library for many people in this day and age, refusing to advance is a complete irresponsibility towards the community the a maintainer of an open source project. Either appoint another maintainer who's more acquainted to the current times or declare the library as deprecated so someone else can fork it and carry on.

Also, censorship goes against everything that open source stands for so please, don't do it unless there's racism or hate speach involved. I wasn't being hateful. If you were moderating Linus Torvalds message's you'd be very busy, then. Don't be a snowflake. I'm merely defending an open source project's interests because it's being held back for an absurd reason.

And this is my piece. Delete it if you will but know you're being unfair and defending a kind of behaviour that should have no place in open source. Thank you.

**Comment by felipearosemena** [comment]
@TheDSCPL His answer is the correct one. Many libraries have their types defined in DefinitelyTyped, if you want to add the type definitions for this, you can do so there. you won't have any pushback to add these type definitions there.

**Comment by jacobangel** [comment]
@TheDSCPL 

Regarding censorship, your comment did not advance any argument or address the merit of @maisano 's statement. I deleted it because it provided no value to the conversation, and substituted name calling in place of a reasoned argument. The comment section of a freely maintained project is not a place reserved for you to scrawl whatever feelings or hot takes you have at the moment. 

As Felipe rightly mentioned, @maisano 's answer is an acceptable path forward for TypeScript support. There is nothing in this decision holding anything back, it's just another avenue. This is OSS, and since you are so acutely aware of the rules of OSS, you know that you are welcome to fork the project if you'd like. 

For future communications, you should aware that the phrase "ok boomer" is a negatively connoted and implies disrespect for the recipient. If you respect the community as much as you say you do, you would be served in improving your respect for those who help maintain it.

**Comment by TheDSCPL** [comment]
Ok. I wasn't scrawling feelings or hot takes.
I feel sorry about this whole convo because I feel it's been blown out of proportion due to miscomunication from my part. I never meant to insult anyone. The message you deleted wasn't thought through and for that I apologise. The second (longer) one directed at you was "rantier" as I didn't like to be censored.
Please let this discussion end here as I feel it started as a shallow and unintentional comment which did sound negative now that I think of it again.
I'm sorry again for this mess. So sorry, in fact that I'll PR @jakelauer's type definitions to the DefinitelyTyped repo myself.

**Comment by TheDSCPL** [comment]
[There we go](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/50877).

The definition's different from this PR because this one's wasn't very accurate and documented.

Edit: It's been merged so you can now find the types at @types/react-router-transition

**Pull request closed without merging**
